
defaults:
  -
    scope:
      path: /docs/
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: /docs/
      type: "pages"
    values:
      permalink: /index.html
      source: resume.md

exclude:
  - README.md
