remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
defaults:
  -
    scope:
      path: "docs" # empty string for the root directory
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "docs" # empty string for the root directory
      type: "pages"
    values:
      permalink: /index.html
      source: resume.md

exclude:
  - README.md
